DROP TABLE PERSON;

CREATE TABLE PERSON
(
ID int primary key,
FIRSTNAME varchar(255),
LASTNAME varchar(255),
PHONE varchar(255)
);

INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, PHONE) VALUES(null,'Sebastian', 'Nielsen', '23456789');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, PHONE) VALUES(null,'Sebastian', 'Nielsen', '23456789');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, PHONE) VALUES(null,'Sebastian', 'Nielsen', '23456789');